CXX=g++
#CPP_FLAGS="-std=c++14"

default:
	$(CXX) -o INT-test int_main.cpp INT.cpp
	$(CXX) -o RINT-test rint_main.cpp RINT.cpp

submission:
	$(CXX) -o INT-demo INTDemo.cpp INT.cpp
	$(CXX) -o RINT-demo RINTDemo.cpp RINT.cpp

